name: playdapp
description: The Playd boilerplate app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  intl: ^0.15.7
  sqflite: any
  path_provider: "^0.4.1"
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/Montserrat-Light.ttf
          weight: 300
        - asset: assets/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/Montserrat-Black.ttf
          weight: 900
        - asset: assets/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
    - family: Raleway
      fonts:
        - asset: assets/Raleway-Thin.ttf
          weight: 100
        - asset: assets/Raleway-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/Raleway-ExtraLight.ttf
          weight: 200
        - asset: assets/Raleway-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/Raleway-Light.ttf
          weight: 300
        - asset: assets/Raleway-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/Raleway-Regular.ttf
          weight: 400
        - asset: assets/Raleway-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/Raleway-Medium.ttf
          weight: 500
        - asset: assets/Raleway-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/Raleway-SemiBold.ttf
          weight: 600
        - asset: assets/Raleway-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/Raleway-Bold.ttf
          weight: 700
        - asset: assets/Raleway-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/Raleway-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/Raleway-Black.ttf
          weight: 900
        - asset: assets/Raleway-BlackItalic.ttf
          style: italic
          weight: 900
    - family: OpenSans
      fonts:
        - asset: assets/OpenSans-Light.ttf
          weight: 300
        - asset: assets/OpenSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/OpenSans-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/OpenSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/OpenSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/OpenSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
  
